# Generated by Django 3.2.5 on 2021-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
