# Generated by Django 3.2.5 on 2021-07-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="dishingredient",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderingredient",
            options={},
        ),
    ]
