# Generated by Django 3.2.5 on 2021-07-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0002_alter_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                through="dishes.DishIngredient", to="dishes.Ingredient"
            ),
        ),
    ]
