# Generated by Django 3.2.5 on 2021-07-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0003_alter_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="dishes.ingredient",
            ),
        ),
    ]
