# Generated by Django 3.2.5 on 2021-07-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0004_alter_dishingredient_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="title",
        ),
    ]
