# Generated by Django 3.2.5 on 2021-07-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0006_auto_20210718_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes",
                through="dishes.DishIngredient",
                to="dishes.Ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="dishingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="di",
                to="dishes.dish",
            ),
        ),
        migrations.AlterField(
            model_name="dishingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="di",
                to="dishes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="orders",
                through="dishes.OrderIngredient",
                to="dishes.Ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="orderingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oi",
                to="dishes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="orderingredient",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oi",
                to="dishes.order",
            ),
        ),
    ]
